server:
  port: 8090

spring:
  application:
    name: api-gateway

  # Configuración del API Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalogService
          uri: lb://catalog-service/
          predicates:
            - Path=/api/v1/catalog/**

  # Configuración de Zipkin
  zipkin:
    base-url: http://localhost:9411
    enabled: true

# Configuración de Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

# Configuración de actuator
management:
  endpoints:
    web:
      exposure:
        include: "info, health"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: "Examen Final - Especialización Backend I"
    description: "Servicio de catálogo de películas y series de televisión"
    authors: {
      author1: "Alberto Gómez Juan",
      author2: "Daniela Calderón Roa"
    }
    version: 1.0.0
  component:
    name: "API Gateway"
    description: "Punto de entrada a la aplicación"
    version: 1.0.0