server:
  port: 0

spring:
  application:
    name: movie-service

  # Configuración de la base de datos
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3370/movie-dev
    username: usr-movie
    password: pwd-movie
    validation-query: SELECT 1
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  
  # Configuración de RabbitMQ para el envío de mensajes
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    
  # Configuración de Zipkin
  zipkin:
    base-url: http://localhost:9411
    enabled: true

# Configuración de las colas
queue:
  movie:
    name: movieQueue

# Configuración de Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

# Configuración de actuator
management:
  endpoints:
    web:
      exposure:
        include: "info, health"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: "Examen Final - Especialización Backend I"
    description: "Servicio de catálogo de películas y series de televisión"
    authors: {
      author1: "Alberto Gómez Juan",
      author2: "Daniela Calderón Roa"
    }
    version: 1.0.0
  component:
    name: "Movie Service"
    description: "Microservicio de películas"
    version: 1.0.0