server:
  port: 0

spring:
  application:
    name: movie-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3370/movie-dev
    username: usr-movie
    password: pwd-movie
    validation-query: SELECT 1
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  zipkin:
    base-url: http://localhost:9411
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

info:
  app:
    name: "Catálogo de Series y Películas"
    description: "Servicio de catálogo de películas y series de televisión"
    authors:
      - "Alberto Gómez Juan"
      - "Daniela Calderón Roa"
    version: 1.0.0
  component:
    name: "Movie Service"
    description: "Movie Service"
    version: 1.0.0

management:
  endpoints:
    web:
      base-path: /actuator
    exposure:
      include: "health,info"
